version: 2
jobs:
  build-and-test:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt"  }}
    - run:
        command: |
          pip install --user -r requirements.txt          
        name: Install Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
    - run:
        command: |
           virtualenv env
           source env/bin/activate
           pip install pytest
           pytest 
        name: Test
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: test-reports    
workflows:
  main:
    jobs:
    - build-and-test
  version: 2


# version: 2.1

# orbs:
#   python: circleci/python@0.2.1

# jobs:
#   build-and-test:
#     executor: python/default
#     steps:
#       - checkout
#       - python/load-cache
#       - python/install-deps
#       - python/save-cache
#       - run:
#           command: ./manage.py test
#           name: Test

# workflows:
#   main:
#     jobs:
#       - build-and-test