version: 2
jobs:
  build-and-test:
    docker:
    - image: circleci/python:latest
    steps:
    - checkout
    - restore_cache:
        keys:
        - pip-{{ checksum "requirements.txt"  }}
    - run:
        command: |
          pip install --user -r requirements.txt          
        name: Install Dependencies
    - save_cache:
        key: pip-{{ checksum "requirements.txt"  }}
        paths:
        - /home/circleci/.local/lib/
    - run:
        command: |
           virtualenv env
           source env/bin/activate
           pip install pytest
           pytest --junitxml=test-results/junit.xml
        name: Test
    - store_test_results:
        path: test-results
       
workflows:
  main:
    jobs:
    - build-and-test
  version: 2

########################################################################
####             Different Config File                           #######
########################################################################
# version: 2.1

# - store_artifacts:
#         path: test-results 
# orbs:
#   python: circleci/python@0.2.1

# jobs:
#   build-and-test:
#     executor: python/default
#     steps:
#       - checkout
#       - python/load-cache
#       - python/install-deps
#       - python/save-cache
#       - run:
#           command: ./manage.py test
#           name: Test

# workflows:
#   main:
#     jobs:
#       - build-and-test


####################################################################
#############      Different Config File/Setting    ################
# version: 2.1
# jobs:
#   run_tests:
#     docker:
#       - image: circleci/python:latest
#     environment:
#       - BASH_ENV: ~/.bashrc
#     steps:
#       - checkout
#       - run:
#           name: Install Python Dependencies
#           command: |
#               echo 'export PATH=/usr/local/bin:$PATH' >> $BASH_ENV
#               pip install --user -r requirements.txt
#       - run:
#           name: Test
#           command: |
#             pytest 
#       - store_test_results:--junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
#           path: test-reports 
#       - store_artifacts:
#           path: test-reports
# workflows:
#   build_tests:
#     jobs:
#       - run_tests