version: 2.1
jobs:
  run_tests:
    docker:
      - images: circleci/python:3.8.1
    enivroment:
      BASH_ENV: ~/.bashrc
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
              echo 'export PATH=~$PATH:~/usr/local/bin' >> $BASH_ENV
              pip install --user -r requirements.txt
      - run:
          name: Test
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports 
      - store_artifacts:
          path: test-reports
workflows:
  build_tests:
    jobs:
      - run_tests


